### ISSUE TITLE
Niech foty doładowują się później

### ISSUE THREAD

**Issue by geodotka** [geodotka/mindtrip#4]
Ważne!

**Comment by piecioshka** [comment]
To może Ci pomóc @geodotka 
https://www.youtube.com/watch?v=516hgt6wbnk

**Comment by piecioshka** [comment]
@geodotka Awesome! :clap:

**Comment by geodotka** [comment]
@piecioshka, Ty to jednak jesteś edukator i mobilizator :clap: Jeszcze nie zdążyłam dobrze przetestować na żywym organizmie, a już obejrzałeś nawet, co natworzyłam.
Dzięki za pomoc!

**Comment by piecioshka** [comment]
Działa lux! :rocket:
